name:  Documentation
description: Mejorar o crear documentaci贸n del proyecto
title: "[DOCS] - "
labels: ["documentation"]
assignees:
  - 
body:
  - type: markdown
    attributes:
      value: |
        ## Documentaci贸n
        Template para tareas de documentaci贸n

  - type: dropdown
    id: doc-type
    attributes:
      label: Tipo de Documentaci贸n
      options:
        - "README.md - Actualizaci贸n"
        - "CLAUDE.md - Gu铆a de arquitectura"
        - "WARP.md - Gu铆a de comandos"
        - "PLAN_TRABAJO.md - Actualizaci贸n de plan"
        - "HEALTHCARE_CONTEXT.md - Contexto de negocio"
        - "VALIDATION_RULES.md - Reglas de validaci贸n"
        - "API_INTEGRATION.md - Integraci贸n de APIs"
        - "UI_PATTERNS.md - Patrones de UI"
        - "User Manual - Manual de usuario"
        - "Developer Guide - Gu铆a de desarrollador"
        - "API Documentation - Comentarios XML"
        - "Diagramas de Arquitectura"
        - "Otro (especificar)"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Prioridad
      options:
        - "Alta - Requerida para pr贸ximo release"
        - "Media - Importante pero no urgente"
        - "Baja - Mejora incremental"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Descripci贸n
      description: 驴Qu茅 documentaci贸n necesita crearse o actualizarse?
      placeholder: |
        Actualizar VALIDATION_RULES.md con:
        - Nuevas reglas de la Fase 2
        - Ejemplos de c贸digo
        - Diagrama de flujo de validaci贸n
    validations:
      required: true

  - type: textarea
    id: content
    attributes:
      label: Contenido Propuesto
      description: Borrador o outline del contenido
      placeholder: |
        ## Nueva Secci贸n
        
        ### Subsecci贸n 1
        - Punto 1
        - Punto 2
        
        ### Subsecci贸n 2
        - C贸digo de ejemplo
        - Diagramas

  - type: textarea
    id: references
    attributes:
      label: Referencias
      description: Fuentes de informaci贸n
      placeholder: |
        - Issue #XX que implement贸 la feature
        - PR #YY con c贸digo relevante
        - Documentaci贸n externa: [URL]

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: Ortograf铆a y gram谩tica revisadas
        - label: Links verificados (no rotos)
        - label: C贸digo de ejemplo compila
        - label: Screenshots/diagramas incluidos (si aplica)
        - label: Consistente con otros documentos
        - label: PR creado y reviewed
